name: JS application

on:
  push:
    branches: [ "master", "dev", "realease_branch/**" ]
  pull_request:
    branches: [ "master", "dev", "realease_branch/**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        with:
          node-version: '20.x'
      - name: Install requirements
        run: |
          npm i
      - name: Build
        run: |
          npm run build